name: Check addon

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install addon checker
      run: |
        pip install -q kodi-addon-checker
        pip install -q -r requirements.txt
        pip install git+https://github.com/romanvm/Kodistubs.git@matrix
    - name: Check with addon-checker
      run: |
        pylint script.tvmaze.scrobbler/libs \
            script.tvmaze.scrobbler/script.py \
            script.tvmaze.scrobbler/service.py
        kodi-addon-checker --branch leia
